### ISSUE TITLE
Build action not working

### ISSUE THREAD

**Issue by wjdenny** [wjdenny/icdsa#1]
The [build action](https://github.com/wjdenny/icdsa/blob/main/.github/workflows/build.yml) doesn't seem to be working like I expected. I'm expecting it to build the site and make it accessible on GitHub pages without creating another branch. I'm not entirely sure how this works. I didn't want a new branch because the generated site shouldn't be version controlled.

There's also the issue of the extra path for the GitHub pages site. I can add a <base> tag to the template, but then it wouldn't find files on local machines. It's messy.

**Comment by wjdenny** [comment]
I think I can get around the base URL issue with environment variables.

```js
module.exports = function(eleventyConfig) {
  // Configuration code...

  // Base URL
  eleventyConfig.addGlobalData("baseUrl", process.env.BASE_URL || "/");
};
```

```yaml
    steps:
      ...
      - name: Build site
        run: |
          export BASE_URL="/icdsa/"
          npm run build
```
